config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources 'users' do
    member do
      patch :change_status
    end
  end

  resources 'likes'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sign_ins#show'
  user_sessions_url = '/sign_ins'
  # get 'login' => 'sign_in#new', :as => :login
  # post 'login' => "sign_in#create"
  # post 'logout' => 'sign_in#destroy', :as => :logout

  resource 'sign_in'

  resources 'students' do
    resources 'comments' do
      post :like, to: 'likes#toggle_liking'
      resources 'answers' do
        post :like, to: 'likes#toggle_liking'
      end
      resources 'objectives'
    end
  end
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user
  has_many :objectives, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :answers, through: :comments
  has_many :likes, through: :comments
  enum scholarity: { initial: 0, elementary: 1, high_school: 2 }
  validates :name, :last_name, presence: true
  validates_format_of :name, :last_name, with: NAMES_FORMAT
  validates :address, presence: true
  validates :birthday, presence: true
  validates :scholarity, presence: true, inclusion: { in: scholarities.keys }
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  before_action :set_student, only: %i[show destroy edit update]
  decorates_assigned :student, :students

  def index
    @filter = StudentFilter.new(Student.all, filter_params)
    @pagy, @students = pagy(@filter.call, overflow: :last_page)
  end

  def show; end

  def new
    authorize Student
    @student = Student.new
  end

  def create
    authorize Student
    @student = current_user.students.build(students_params_add)
    unless @student.save
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @student
  end

  def update
    authorize @student
    unless @student.update(students_params_add)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @student
    if @student.destroy
      redirect_to students_path
    else
      render :new
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def students_params_add
    params.require(:student).permit(:name, :last_name, :address, :birthday, :scholarity, :goes_to_school)
  end

  def filter_params
    params.fetch(:student_filter, {}).permit(
      :query
    )
  end
end

app/views/students/_form.html.erb
<%= form_with model: @student, class:"form_margin_top" do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class:"textBox"%>
    <div class="error_message"><%= @student.errors[:name].to_sentence%></div>

    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"textBox"%>
    <div class="error_message"><%= @student.errors[:last_name].to_sentence%></div>

    <%= form.label :birthday %>
    <%= form.date_field:birthday, class:"textBox"%>
    <div class="error_message"><%= @student.errors[:birthday].to_sentence%></div>

    <%= form.label :address %>
    <%= form.text_field :address, class:"textBox"%>
    <div class="error_message"><%= @student.errors[:address].to_sentence%></div>

    <%= form.label :scholarity %>
    <%= form.select(:scholarity,Student.scholarities.keys, { }, { class: "textBox" } ) %>
    <div class="error_message"><%= @student.errors[:scholarity].to_sentence%></div>

    <%= form.label :goes_to_school, t('.goes'), class:'radio-buttons-label' %>
    <section class="radio-buttons">   
      <%= form.radio_button(:goes_to_school, true) %>
      <%= form.label(:assists, t('.true')) %>

      <%= form.radio_button(:goes_to_school, false) %>
      <%= form.label(:assists, t('.false')) %>
      <div class="error_message"><%= @student.errors[:goes_to_school].to_sentence%></div>
    </section>
    <%= form.submit 'Registrar Estudiante', class:"btn new_user" %>
<% end %>

app/views/students/_student.html.erb
<tr id="<%= dom_id(student)%>">
  <td class="table_field table_name"><%= link_to student.full_name, student, class:"table-field" %></td>
  <td class="table_field"><%= student.age %></td>
  <td class="table_field"><%= student.school %></td>
  <td class="table_field"><%= t(".#{student.goes}") %></td>
  <td>
    <%=link_to image_tag("edit.png", class:"icon_edit"), edit_student_path(student), data: {turbo_frame: "modal"} if policy(student).edit?%>
    <%=link_to student_path(student), data: {turbo_method: :delete, turbo_confirm: t('.delete_warning') } do %>
    <%= image_tag("delete.png", class:"icon_delete") if policy(student).delete? %>
    <% end %>
  </td>
</tr>

app/views/students/create.turbo_stream.erb
<turbo-stream action="prepend" target="students">
  <template>
    <%= render student %>
  </template>
</turbo-stream>
<turbo-stream action="update" target="modal">
  <template>
  </template>
</turbo-stream>

app/views/students/edit.html.erb
<section class="index_user">
<%= turbo_frame_tag :modal do %>
  <div class="modals"data-controller="turbomodals">
    <div class="form_container">
      <div class="title">
        <h1 class="add_edit_title"><%= t('.tittle')%></h1>
      </div>
        <%= render "form", student: @student %>
        <button data-action="click->turbomodals#submitEnd">cerrar</button> 
      </div>
    </div>
  </div>
  <% end %>
</section>

app/views/students/index.html.erb
<section class="index_user">
  <div class="filter_user">
    <%= form_with(model: @filter, url: students_path, method: :get, class: "form_user") do |form| %>
      <%= form.search_field :query, class:"search-field"%>
      <button type="submit" class="search-button">
        <%= image_tag 'search.png' %>
      </button>
    <% end %>
    <%= link_to new_student_path, data:{turbo_frame: "modal"}, class: 'btn new_user' do %>
      <%= image_tag("Adduser.png", class: 'icon_add') %>
      <%= t('.new_student') %>
    <% end if policy(Student).new?%>
  </div>
  <section>
    <table class='users_table'>
      <thead>
        <tr class='head_table'>
          <th class='name'><%= t('.student') %></th>
          <th class='name'><%= t('.age') %></th>
          <th class='name'><%= t('.schooling_attained') %></th>
          <th class='name'><%= t('.schooled') %></th>
        </tr>
      </thead>
      <tbody id="students">
        <%= render students %>
      </tbody>
    </table>
  </section>
  <footer style="text-align: center;">
    <%== pagy_nav(@pagy) %>
  </footer>
</section>

app/views/students/new.html.erb
<section class="index_user">
<%= turbo_frame_tag :modal do %>
  <div class="modals"data-controller="turbomodals">
    <div class="form_container">
      <div class="title">
        <h1 class="add_edit_title"><%= t('.tittle') %></h1>
      </div>
      <%= render "form", student: @student %>
      <button data-action="click->turbomodals#submitEnd">cerrar</button> 
    </div>
  </div>
<% end %>
</section>

app/views/students/show.html.erb
<section>
  <header class="superior">
    <p><%= t('.students') %><span class="name"> <%= student.full_name%> </span></p>
  </header>

  <div class="row">
    <div class="row-left" data-controller="add">
      <h2><%= student.full_name%></h2>
      <h4 class="name"><%= t('.student_data') %></h4>
      <p><%= student.address %></p>
      <h4><%= t('.schooling_attained') %></h4>
      <p><%= student.school %></p>
      <h4><%= t('.schooled') %></h4>
      <p><%= t(".#{student.goes}") %></p>
      <h4><%= t('.fav_assignment') %></h4>
      <h4><%= t('.dif_assignment') %></h4>
      <h4 class="name"><%= t('.objective') %></h4>
      <p><% student.objective_list.each do |obj|  %>
        <input data-add-target="todo" data-action="click->add#task" type="checkbox"><%= obj %>
        <%end if policy(Objective).index? %>
      </p>
    </div>

    <div class="row-right">
      <h4 class="comments"> <%= t('.comms') %> </h4>
      <div>
        <%= render 'comments/comments_form' %>
        <div class="comments_list">
          <%= render student.comments_list.where(highlight: true), klass: "coment highlight" %>
          <%= render student.comments_list, klass: "coment" %>
        </div>
      </div>
    </div>
</section>

app/views/students/update.turbo_stream.erb
<turbo-stream action="replace" target='<%= dom_id(student) %>'>
  <template>
    <%= render student %>
  </template>
</turbo-stream>
<turbo-stream action="update" target="modal">
  <template>
  </template>
</turbo-stream>