config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources 'users' do
    member do
      patch :change_status
    end
  end

  resources 'likes'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sign_ins#show'
  user_sessions_url = '/sign_ins'
  # get 'login' => 'sign_in#new', :as => :login
  # post 'login' => "sign_in#create"
  # post 'logout' => 'sign_in#destroy', :as => :logout

  resource 'sign_in'

  resources 'students' do
    resources 'comments' do
      post :like, to: 'likes#toggle_liking'
      resources 'answers' do
        post :like, to: 'likes#toggle_liking'
      end
      resources 'objectives'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :students
  has_many :objectives, through: :students
  has_many :comments, through: :students
  has_many :answers, through: :students
  has_many :likes, dependent: :destroy
  enum rol: { admin: 0, colab: 1 }
  validates :name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: EMAIL_FORMAT
  validates_format_of :name, :last_name, with: NAMES_FORMAT
  validates :password, length: { minimum: 3 }, allow_nil: false, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, allow_nil: false, if: lambda {
                                                                            new_record? || changes[:crypted_password]
                                                                          }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update change_status]
  decorates_assigned :user, :users

  def index
    @filter = UserFilter.new(User.all, filter_params)
    @pagy, @users = pagy(@filter.call)
  end

  def new
    authorize User
    @user = User.new
  end

  def show
    @user
  end

  def create
    authorize User
    @user = User.new(user_params)
    unless @user.save
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    unless @user.update(user_params_edit)
      render :edit, status: :unprocessable_entity
    end
  end

  def change_status
    authorize User
    @user.toggle!(:status)
    render user, layout: false
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params_edit
    params.require(:user).permit(:name, :last_name)
  end

  def user_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end

  def filter_params
    params.fetch(:user_filter, {}).permit(
      :query
    )
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, class:"form_margin_top" do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class:"textBox"%>
    <div class="error_message"><%= @user.errors[:name].to_sentence%></div>
   
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"textBox" %>
    <div class="error_message"><%= @user.errors[:last_name].to_sentence%></div>

    <%= form.label :email %>
    <%= form.text_field :email, class:"textBox" %>
    <div class="error_message"><%= @user.errors[:email].to_sentence%></div>

    <%= form.label :password %>
    <%= form.text_field :password, class:"textBox" %>
    <div class="error_message"><%= @user.errors[:password].to_sentence%></div>

    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation, class:"textBox" %>
    <div class="error_message"><%= @user.errors[:password_confirmation].to_sentence%></div>

    <%= form.submit t('.register_button'), class:"btn new_user" %>

<% end %>

app/views/users/_form_edit.html.erb
<%= form_with model: @user, class:"form_margin_top" do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class:"textBox"%>
    <div class="error_message"><%= @user.errors[:name].to_sentence%></div>
   
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"textBox" %>
    <div class="error_message"><%= @user.errors[:last_name].to_sentence%></div>

    <%= form.label :email %>
    <%= form.text_field :email, class:"textBox", disabled:true%>
    <div class="error_message"><%= @user.errors[:email].to_sentence%></div>

    <%= form.submit t('.save_button'), class:"btn new_user" %>
<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id(user)%>" data-controller="block" data-block-url-value="<%= change_status_user_path(user)%>">
  <td class= "table_field table_name"><%= user.full_name%></td>
  <td class= "table_field"><%= user.email%></td>
  <% if policy(user).edit?%>
    <td class= "table_field"><%= user.status if policy(user).change_status?%></td>
    <td class= "table_field"><%= user.rol if policy(user).edit? %></td>
    <td><%= link_to t('.edit_user'), edit_user_path(user), data:{turbo_frame: "modal"} if policy(user).edit? %></td>
    <%if policy(user).change_status? %>
      <td><button id="<%= dom_id(user, :button)%>"
          data-action= "click->block#changeStatus">
          <%= t('.toggle_button') %></button></td>
    <%end%>
  <%end%>
</tr>

app/views/users/create.turbo_stream.erb
<turbo-stream action="prepend" target="users">
  <template>
    <%= render user %>
  </template>
</turbo-stream>
<turbo-stream action="update" target="modal">
  <template>
  </template>
</turbo-stream>

app/views/users/edit.html.erb
<section class="index_user">
<%= turbo_frame_tag :modal do %>
  <div class="modals" data-controller="turbomodals">
    <div class="form_container">
      <div class="title">
        <h1 class="add_edit_title"><%= t('.tittle') %></h1>
      </div>
      <button data-action="click->turbomodals#submitEnd">cerrar</button> 
      <%= render "form_edit", user: @user %>
    </div>
  </div>
<% end %>
</section>

app/views/users/index.html.erb
<section class="index_user">
  <div class="filter_user">
    <%= form_with(model: @filter, url: users_path, method: :get, class: "form_user") do |form| %>
    <%= form.search_field :query, class:"search-field"%>
    <%= form.button class:"search-button" do %>
    <%= image_tag 'search.png'%>
    <% end %>
    <% end %>
    <%= link_to image_tag("Adduser.png", class: 'icon_add')+t('.new_user'), 
        new_user_path,  data:{turbo_frame: "modal"}, class: 'btn new_user' if policy(User).new?%>
  </div>
  <section>
    <table class='users_table'>
      <thead>
        <tr class='head_table'>
          <th class='name'><%= t('.users') %></th>
          <th class='name'><%= t('.email') %></th>
          <% if policy(User).edit? %>
            <th class='name'><%= t('.active') %></th>
            <th class='name'><%= t('.rol') %></th>
            <th class='name'><%= t('.actions') %></th>
            <th class='name'><%= t('.activate') %></th>
          <%end%>
        </tr>
      </thead>
      <tbody id="users">
        <%= render users %>
      </tbody>
    </table>
  </section>
  <footer style="text-align: center;">
    <%== pagy_nav(@pagy) %>
  </footer>
</section>

app/views/users/new.html.erb
<section class="index_user">
<%= turbo_frame_tag :modal do %>
  <div class="modals" data-controller="turbomodals">
  <div class="form_container">
    <div class="title">
      <h1 class="add_edit_title"><%= t('.tittle') %></h1>
    </div>
    <button data-action="click->turbomodals#submitEnd">cerrar</button> 
    <%= render "form", user: @user %>
  </div>
  </div>
<% end %>
</section>

app/views/users/show.html.erb
<h3><%=t('.welcome', name: current_user.name)%>!</h3>
<h4><%=t('.ur_email', email: current_user.email)%></h4>
<%= button_to t('.logout'), sign_in_path , method: :delete %>

app/views/users/update.turbo_stream.erb
<turbo-stream action="replace" target='<%= dom_id(user) %>'>
  <template>
    <%= render user %>
  </template>
</turbo-stream>
<turbo-stream action="update" target="modal">
  <template>
  </template>
</turbo-stream>