config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources 'users' do
    member do
      patch :change_status
    end
  end

  resources 'likes'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sign_ins#show'
  user_sessions_url = '/sign_ins'
  # get 'login' => 'sign_in#new', :as => :login
  # post 'login' => "sign_in#create"
  # post 'logout' => 'sign_in#destroy', :as => :logout

  resource 'sign_in'

  resources 'students' do
    resources 'comments' do
      post :like, to: 'likes#toggle_liking'
      resources 'answers' do
        post :like, to: 'likes#toggle_liking'
      end
      resources 'objectives'
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :comment
  belongs_to :student
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, presence: true
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :set_student, only: %i[create delete give_like]
  before_action :set_answer, only: %i[show give_like update delete]
  decorates_assigned :answer, :answers

  def new
    @answer = Answer.new
  end

  def create
    @comment = Comment.find(params[:comment_id])
    @answer = @comment.answers.build(answer_params.merge(user: current_user, student: @student))
    if @answer.save
      redirect_to(student_path(@student), notice: t('.success'))
    else
      render @student, status: :unprocessable_entity
    end
  end

  def show; end

  def index
    @answer = Answer.all
  end

  def delete
    if @answer.destroy
      redirect_to(student_path(@student), notice: t('.success'))
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to(student_path(@student), notice: t('.success'))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def give_like
    sum = @answer.likes += 1
    @answer.update(likes: sum)
    render json: { answer: @answer }
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :likes)
  end

  def set_student
    @student = Student.find(params[:student_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/views/answers/_answer.html.erb
<div class="comment_answer" data-controller="give"
  data-give-url-value="<%= student_comment_answer_like_path(answer.student_id, answer.comment_id, answer)%>">
  <p class="user_name_comment"><%= answer.name %></p>
  <strong><%= answer.time %></strong>
    <button data-action="click->give#giveLike" class="like_img">
      <%= image_tag('like.png') %>
    </button>
  <span class="like answer_like_<%= answer.id %>" id="<%= dom_id(answer, :span)%>" data-give-target="likeCount">
    <%= Like.where(likeable: answer).count%>
  </span>
  <p><%= answer.content %></p>
</div>

app/views/answers/_answer_form.html.erb
<%= form_with(model: [@student, comment, Answer.new]) do |f| %>
  <%= f.text_area :content, class:"text_comment answer", placeholder: t('.placeholder') %>
  <%= f.submit 'Answer', class: "btn new_user" %>
<% end %>