config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources 'users' do
    member do
      patch :change_status
    end
  end

  resources 'likes'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sign_ins#show'
  user_sessions_url = '/sign_ins'
  # get 'login' => 'sign_in#new', :as => :login
  # post 'login' => "sign_in#create"
  # post 'logout' => 'sign_in#destroy', :as => :logout

  resource 'sign_in'

  resources 'students' do
    resources 'comments' do
      post :like, to: 'likes#toggle_liking'
      resources 'answers' do
        post :like, to: 'likes#toggle_liking'
      end
      resources 'objectives'
    end
  end
end

app/views/layouts/_navbar.html.erb
<section class="nav_header">
  <nav class="nav_pad">
    <ul class="nav_links">
      <li class="nav_menu"><%= link_to image_tag("menu-desplegable.png"), class:"nav_item" %></li>
      <li><%= link_to image_tag("home.png"), users_path, class:"nav_item" %></li>
      <li><%= link_to "Students", students_path, class:"nav_item" %></li>
      <li class="nav_user"><%= link_to current_user.name, user_path(current_user), class:"nav_item"%></li>
    </ul>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TardeDeBarrio</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
  <%= render "layouts/navbar"%>
  <% if logged_in? %>
  <!--render nav--->
  <% end %>
  <%= turbo_frame_tag :modal %>
  <section>
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <% if flash[:error] %>
    <%= flash[:error] %>
    <% end %>
  </section>
  <%= yield %>
</body>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TardeDeBarrio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>



  </head>
  <body class="body_login">
    <%= yield %>
  </body>
</html>